version: "3.9" # Version cua docker 

services: # list cac containers trong project can chay
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000" # Port backend
    volumes: 
      - ./backend:/api # Mount thu muc backend vao container
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000" # Port frontend
    volumes:
    - ./frontend:/app
    - /app/node_modules
    networks:
      - app-network
  
  ollama:
    build:
      context: ./ollama
    container_name: ollama-server
    image: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network
    entrypoint: ["sh", "/pull.sh"]

networks:
  app-network:
    # bridge network la mang noi bo (virtual network) tren cung may host de ket noi cac container voi nhau
    driver: bridge

volumes:
  ollama-data: