services:
# neu bo container_name thi default: <project_name>_<service_name>_<số_thứ_tự>
  ollama:
    # container_name: ollama-server-container
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network

  qdrant:
    # container_name: qdrant-container
    image: qdrant/qdrant:v1.15.0
    ports:
      - "6333:6333" # http api
      - "6334:6334" # gRPC api 
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - app-network

  postgres:
    # container_name: postgres-container
    image: postgres:15
    restart: unless-stopped # auto restarting when the service is error.
    environment:
    # ${VAR:-default_value}: get VAR if exist else return default_value.
      POSTGRES_USER: ${POSTGRES_USER:-raguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ragpassword}
      POSTGRES_DB: ${POSTGRES_DB:-ragdatabase}
    volumes:
      # /docker-entrypoint-initdb.d/ is a special location in container.
      # if the service runs for the first time, then container will check /docker-entrypoint-initdb.d/ for .sql file and execute them.
      # else if postgress-data already exists, the service will skip executin .sql files in /docker-entrypoint-initdb.d/.
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    # container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com   # email đăng nhập
      PGADMIN_DEFAULT_PASSWORD: secret_password # mật khẩu đăng nhập
    ports:
      - "5050:80"                               # truy cập web tại http://localhost:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin           # lưu dữ liệu cấu hình
      - ./servers.json:/pgadmin4/servers.json:ro
    user: "5050:5050"
    networks:
      - app-network
    depends_on:
      - postgres # dam bao postgres duoc khoi dong truoc pgadmin

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    # container_name: backend-container
    ports:
      - "8000:8000"
    volumes: 
      - ./backend:/app
      # - backend-uploads:/app/vectordb/data
    networks:
      - app-network
    depends_on:
      - ollama
      - qdrant
      - postgres

    env_file: # neu su dung environment se ghi de len env_file neu trung gia tri
      - ./backend/.env 
    # environment: # ghi de len .env neu bien khai bao trung nhau.
    #   - POSTGRES_HOST=postgres
    #   - QDRANT_HOST=qdrant
    #   - OLLAMA_BASE_URL=http://ollama-server-container:11434

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
    # we create an empty folder at /app/note_modules 
    # because:
    # 1. when this service runs in the first time, node_modules doesn't exist, so all folders from host will be mounted to container.
    # 2. later, node_models is created by npm inside container, but without this volume mapping, it would be overwritten and disappear due to the bind mount.
      - ./frontend:/app
      - /app/node_modules 
    networks:
      - app-network
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.development
      - ./frontend/.env.production
    # environment:
    #   - REACT_APP_API_URL=http://localhost:8000

networks:
  app-network:
    driver: bridge

volumes:
  ollama-data:
  qdrant-data:
  postgres-data:
  pgadmin-data:
  backend-uploads:
