services:
  ollama:
    container_name: ollama-server-container
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network
    # runtime: nvidia   # Tùy bạn, chỉ bật khi cần GPU

  qdrant:
    container_name: qdrant-container
    image: qdrant/qdrant:v1.15-gpu-nvidia
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - app-network
    # runtime: nvidia
    # Nếu không cần GPU thì có thể đổi image:
    # image: qdrant/qdrant:v1.15.0

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes: 
      - ./backend:/home/backend
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ollama
      - qdrant
    env_file:
      - .env
    # hoặc, nếu bạn không dùng .env, hãy thêm:
    # environment:
    #   - OLLAMA_HOST=http://ollama-server-container:11434

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama-data:
  qdrant-data:
